name: Deploy to EC2 Amazon Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 black
          if [ -f spark/requirements.txt ]; then pip install -r spark/requirements.txt; fi
          if [ -f airflow/requirements.txt ]; then pip install -r airflow/requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.git,__pycache__,venv
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=.git,__pycache__,venv

      

      - name: Test Spark jobs (if tests exist)
        run: |
          if [ -d "spark/tests" ]; then
            cd spark
            python -m pytest tests/ -v || true
          fi

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Amazon Linux EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to project directory
            cd ${{ secrets.PROJECT_PATH }}
            
            # Pull latest changes
            git pull origin main
            
            # Make scripts executable
            chmod +x scripts/*.sh
            
            # Run deployment
            ./scripts/deploy.sh
            
            # Show final status
            echo "Deployment completed. Checking final status..."
            docker compose ps